### ISSUE TITLE
import list of all the Person powertakers of a group

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#25]
**PR**

- https://github.com/buzzn/core/pull/1348
- https://github.com/buzzn/core/pull/1353
- https://github.com/buzzn/core/pull/1355
- https://github.com/buzzn/admin-app/pull/260
- https://github.com/buzzn/core/pull/1368

----

**Story**
As PhO I want to import and see all the Persons powertakers according to the group they belong to in a list.

---
**DoD**

- [x] Show a list with two tabs: 
  - [x] tab 1: has 5 columns and constist of current powertakers: Name/lastname, register name, contract number, startdate, status (active)
  - [x] tab 2: historic pts, consists of 6 columns. same as list one + "End date" of the contract. status of these pts is "ended"
- [x] link register name to register detail page

excluded as long we don´t have the detail pages:  
- link pt name to the pt-detail page (#51 )
- link the contract number to the contract--data details page (#115 )
- organisations data #130

---
**XD**

- [x] prepare list of PTs and use this screen: https://projects.invisionapp.com/d/main#/console/12205665/256909734/comments

- [x] the list is sorted from A-Z acoording to the powertaker Name

- [x] In the list I see 4 columns, 1. Name, 2. the register name, 3. status, 4. startdate of the contract in the list like here: https://staging-console.buzzn.io/admin/groups/2c7d6a7d-d51c-4e72-9811-e3a593256938

list tab 1:  current https://projects.invisionapp.com/d/main#/console/12205665/256909734/comments 

list tab2: List of former powertakers
https://projects.invisionapp.com/d/main#/console/12205665/273358584/preview

---

**Technical details**

_Frontend_

- [x] extend existing powertakers list to show above data (make sure to localize dates and status text) for active power takers
- [x] link to register detail page
- [x] add tab navigation to toggle between active and historical power takers
- [x] add list of historical power takers (which also shows contract end date). Power takers are historical when the status field is "ended"
- [x] localize table headers

_Backend_

- [x] import contract data 
   - [x] from beekeeper table `minipool_sn` where `drittbelieferung` is 0 and kontaktdaten.rechtsform is "Privatperson"
  - [x] get title, prefix, first and last name from the `kontaktdaten` table (foreign key is `kontakt_id`)
  - [x] also get telefon and email from the kontaktdaten table
  - [x] link to the correct register by using the buzznid field (ignore zählernummer)
  - [x] import contract number: create minimal localpool powertaker contract. Store `vertragsnummer` in `contract_number` and `nummernzusatz` in `contract_number_addition`
  - [x] link to the correct localpool, contractor (always group owner). Ignore bank accounts for now, done in later tickets
  - [x] import start and end dates (ignore status text field).
- [x] adapt API: send contract_number and contract_number_addition combined in one field
- [x] fix status logic for begin and ended. Set signing date to begin date, termination date to end date.
- [x] make sure to strip imported text fields as there often are leading spaces

**Comment by dottorer** [comment]
Notes per talk with Pho:
- PTs do not have a customer number (as in '80343') since they are not Buzzn Customers, but PG customers. Hence they can be referenced by their PT contract number which is the number of the LGPc (see [Glossary](https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/201064461/Glossary)) plus a sequence number. So it is something like "60050/7", which is their customer_number.
- Each register needs to have gapfree PTc since group start. Therefore we need a series of PTcs with the following. For a given "60050/7" 
-- we need the first PTc to begin on group start date.
-- we need each end_dt to be the same as begin_dt of next contract. End_dt here means first day of No Service. This way the end and being have always some register reading value.
-- if there is a gap > 1 day between contracts, then we need to insert a "vacancy contract" which means a contract whereby the group management company ("Hausverwaltung") is paying for any used power.
-- we can identify the group management company by looking at the customer that pays for the 'Allgemeinstrom'. To hack it, Pho will enter this into the unused field sea4_buzznid for us so we can pinpoint it.

**Comment by evaklopp** [comment]
@dottorer we should avoid to mix the list of PTs with the List of contracts or registers of a group. I´m not sure if the PTs list is the right place to show the gapless history of a register. This is part of the register detail in the contracts tab: https://projects.invisionapp.com/d/main#/console/12205665/266638569/preview

so what we should display here is a list of all current powertakers, and maybe a history-list of former powertakers to access them. These lists does need a Name, number to identify the contract, the register name and the begin date of the contract. The name should link to the pt-details. The number to identify the contract links to the contract, the registername to the register and its history. What do you think?

**Comment by dottorer** [comment]
@evaklopp You are correct, the intention is not to mix PTs here. My comments above were just for overall background info. Your proposal is spot on! :-)

I think we should:
- display a list of current power takers of the group (both group supplied and third party supplied)
- possibly a link to toggle to a list of 'former PTs' (and toggle back to 'active PTs')
see example from Lale.help as an idea..
![image](https://user-images.githubusercontent.com/14217285/33438343-d62777d6-d5ea-11e7-9cc5-fb91a6e0476b.png)
- As you state the list should be as follows
-> PT name (links to Person details)
-> Contract number (e.g. 60034/12 for the 12th PT contract in LGPc 60034; links to contract details)
-> Register name (links to register detail)

**Comment by dottorer** [comment]
The person data for the PT should be pretty straight forward using this basic SQL to draw the data from:

`SELECT 
sn.vertragsnummer,
sn.nummernzusatz,
sn.buzznid as Registernummer,
sn.drittbelieferung,
ger.zählernummer as Zählernummer,
--sn.vertragspartner,
--sn.vertragskontonummer,
sn.kontakt_id,
kont.anrede,
--kont.titel,
kont.vorname,
kont.nachname,
kont.telefon,
kont.email,
addr.adress_id as SN_addr_id,
addr.strasse as SN_strasse,
addr.hausnummer as SN_hausnummer,
addr.plz as SN_PLZ,
addr.stadt as SN_Stadt
--addr2.adress_id as Bezug_id,
--addr2.strasse as Bezug_strasse,
--addr2.hausnummer as Bezug_hausnummer,
--addr2.plz as Bezug_PLZ,
--addr2.stadt as Bezug_Stadt

FROM minipooldb.minipool_sn sn, minipooldb.adresse addr, minipooldb.adresse addr2, minipooldb.kontaktdaten kont, minipooldb.msb_gerät ger 

WHERE sn.adress_id = addr.adress_id
AND sn.adress_id_bezug = addr2.adress_id
AND sn.kontakt_id = kont.kontaktdaten_id
AND sn.buzznid = CONCAT(ger.vertragsnummer || '/' || ger.nummernzusatz)
--AND sn.drittbelieferung = '1'
--AND sn.vertragsnummer = '60050'

ORDER BY sn.vertragsnummer ASC, sn.nummernzusatz ASC `

**Comment by phillipoertel** [comment]
@dottorer There are a few inconsistencies in the status of the contracts (end_date and status contradict each other), could you clarify with PhO?

![bildschirmfoto 2018-01-15 um 09 36 07](https://user-images.githubusercontent.com/5188/34934327-62b2b54a-f9da-11e7-8ca0-24201a0b9579.png)
![bildschirmfoto 2018-01-15 um 09 48 44](https://user-images.githubusercontent.com/5188/34934328-62ca9430-f9da-11e7-8357-743ff7f15c9d.png)

**Comment by mkristian** [comment]
already combining contractnumber and contractnumber-addition to one field.

**Comment by phillipoertel** [comment]
@dottorer in the table kontaktdaten the following entries are labeled as "Privatperson", but the data doesn't look like it. Do we need to clean this up? If so, it would be easiest if Philipp does it.

![bildschirmfoto 2018-01-16 um 17 56 03](https://user-images.githubusercontent.com/5188/35001192-8fd2ceb8-fae6-11e7-9b99-43ec55adad78.png)

The query for this data was:

```sql
select kontaktdaten_id, anrede, geschlecht, vorname, nachname, firma, rechtsform 
  from kontaktdaten 
  where vorname = '' 
  and rechtsform = 'Privatperson'
  and (geschlecht = 'Firma' or nachname ~ 'Wogeno|IFAGE|Gemeinde|DomagkPark')
```

**Comment by phillipoertel** [comment]
There are also 49 entries where the `minipool_sn.drittbelieferung` flag and `kontaktdaten.nachname` seem to contradict each other:

![bildschirmfoto 2018-01-16 um 18 07 28](https://user-images.githubusercontent.com/5188/35001875-2b2b26c0-fae8-11e7-9ee5-5fbeda947dac.png)

Query:

```sql
select 
  K.kontaktdaten_id as "kontaktdaten.kontaktdaten_id", 
  K.vorname as "kontaktdaten.vorname", 
  K.nachname as "kontaktdaten.nachname", 
  SN.drittbelieferung as "minipool_sn.drittbelieferung"
from minipool_sn SN 
join kontaktdaten K on SN.adress_id=K.kontaktdaten_id 
where SN.drittbelieferung=0 and K.nachname LIKE '%dritt%'
```

The other way around (drittbeliefert flag is set but not actually drittbeliefert) may also have inconsistencies?

![bildschirmfoto 2018-01-16 um 18 09 29](https://user-images.githubusercontent.com/5188/35001961-6bf3dea4-fae8-11e7-82b8-9d34a4fedd18.png)

**Comment by phillipoertel** [comment]
I noticed the kontaktdaten table has many duplicates. Especially Wogeno/Cohaus and Wagnis eG have many, slightly different records Do we need to clean them up, i.e. only make one person or organization record in our DB? If so, I suggest we do that in a separate story.

<img width="504" alt="bildschirmfoto 2018-01-16 um 18 26 34" src="https://user-images.githubusercontent.com/5188/35002812-220be306-faeb-11e7-8add-a81cd7768595.png">

**Comment by phillipoertel** [comment]
As discussed I merge different records from the beekeeper kontaktdaten table that have the same email, first and last name into one person record on our side. But we may loose data that way, maybe they were separate records in beekeeper for a reason ... to clarify.

**Comment by dottorer** [comment]
@phillipoertel I think for the query question on 'drittversorgt' we should join in kontakt_id as
`join minipooldb.kontaktdaten K on SN.kontakt_id=K.kontaktdaten_id `
,no ? 

I also spoke with Pho on the multiple instances of persons and how to collapse them. Let's connect in the office.

**Comment by dottorer** [comment]
Also, we there are no inconsistencies between eeg_umlage = '0' and drittbelieferung = 1. I think we should not carry forward the value eeg_umlage = '0' but track this only in the boolean for thrid party supplied = YES. the EEG_Umlage should only track full/reduced and be not applicable if drittbelieferung = YES (they are mutually exclusive and if drittbelifert we do not care about EEG at all; Pho confirmed this was a crutch in BK).

**Comment by phillipoertel** [comment]
To clarify:
- [ ] inconsistencies "drittbeliefert"
- [ ] duplicates in kontaktdaten
- [ ] eeg umlage
- [ ] privatperson/gewerblich

**Comment by phillipoertel** [comment]
@dottorer beekeeper contracts always have an end_date, even if it's just a 2050-12-31. Is that date really in the contract, or just a hack/beekeeper limitation? In the latter case, we could leave the end_date blank on import, then only really terminated contracts would show contain a value.

**Comment by dottorer** [comment]
Any 2050 or 2099 or some funny future date should be blank end dates on our end. Those are indeed bk hacks.

**Comment by phillipoertel** [comment]
FYI only these registers couldn't be imported (likely the virtual ones):
- 60014/9 (yes this is the buzznid in the minipool_sn table. "Nicole Gerke", no meter serial)
- 90005/5
- 90043/1
- 90049/5

**Comment by phillipoertel** [comment]
The story is testable on staging. 

What is excluded/letft to do at some point:
- import virtual meters (https://github.com/buzzn/scrum/issues/25#issuecomment-358358038). right now contracts are imported with a fake input meter of the name "FAKE-FOR-IMPORT"
- deduplicate powertakers -- we could do that in the context of the organizations story. persons should already be deduplicated quite nicely.
- review of labeling the powertaker as Person or Organization (Privatperson or Gesellschaft) --> waiting for feedback from PhO

**Comment by scsirdx** [comment]
@evaklopp There is a bug in register link. I'm fixing it outside of this ticket. So links are there (and they're correct), but when you click on them, you'll be redirected to the meter page.

**Comment by scsirdx** [comment]
@evaklopp I fixed it (and added basic loading component). So you can test it.

**Comment by dottorer** [comment]
@scsirdx Couple of first glance questions:
- the powertaker tab is still hidden in Devmode, can we open it up now?
- should the i18n for list column titles be there already?
- sorting on the start date column does not sort them by date really.
- page header should be 'Powertakers' and not 'Localpool powertakers'

**Comment by dottorer** [comment]
@phillipoertel @evaklopp Long deep dive with Pho. Some results to implement:

- minippol_sn.buzznid '60014/9' was indeed data error and we corrected it in BK.
- buzznid 90005/5 and 90043/1 are indeed virtual consumption meters as 'substitution registers' a la Kirchhoff formula -> can be calculated.
- buzznid 90049/5 is a complex special case and needs to be deferred until we have full formula editing for VRs.
- all entries in kontaktdaten with  email 'philipp@buzzn.net' are data garbage and have no entry in minipool_sn. ignore.
- for the consumption register of a power generation meter we should ideally create a PTcontract with the 'default customer' (WEG, etc) of the group as power taker and `EEG = none`.
- For third party supplied, we do NOT need to know the customer in any detail. Nor the power supplier really (no grid mix needed). All we need is to track for that register from when to when we do not need to bill this register. And of course we need to know this register is thrid party supplied so we can calculate the corrected ÜGZ. This all means we can really stub out the import of third party contracts down to register and begin/end. Let's discuss how to do this best...

**Comment by scsirdx** [comment]
@dottorer 
1. fixed
2. please, provide translations. I used text from the invision prototype
3. fixed
4. fixed

**Comment by dottorer** [comment]
@scsirdx I added some translations in the i18n DE files to be pulled in on next build. However, the page title 'Powertakers' seems still hardcoded and should be i18n to 'Stromnehmer'. Overall, this did not get the col headings from the codeship build into Staging...

**Comment by evaklopp** [comment]
@scsirdx @phillipoertel 
1. I still see the tabs names and the column names of the list not propperly, still like this: ADMIN.CONTRACTS.NAVACTIVEPOWERTAKERS same for column names
2. second, if I click on one of the registers listed, I get the error "Ican´t remember what you requested" Even after refreshing the whole page.  
3. after clicking on the register, the linked page is the correct page "register detail", but wrong tab: Please open the first tab of the register detail page, "readings". 
3. the group "Bismarkstraße" has no powertakers at all, neither in the console data? 
4. Breadcrumb is not shown properly if I click on the powertakers-page of a group. looks like: My groups/ / Powertakers
5. question: can we show breadcrumbs in german aswell?

**Comment by dottorer** [comment]
@scsirdx  Status field in list should also show i18n values per the valid states of a contract:

onboarding = "Im Wechselprozess"
active = "In Belieferung"
terminated = "Gekündigt"
ended = "Beendet"

**Comment by phillipoertel** [comment]
@dottorer the "Privatperson" inconsistencies mentioned in https://github.com/buzzn/scrum/issues/25#issuecomment-358029224 are handled in the latest dump/import.

**Comment by scsirdx** [comment]
@evaklopp Please, provide the broken link/register name for the 2nd issue and translations for the 6th. All other frontend related issues are fixed.
@dottorer Translations are there. And i added a workaround, so no more cache clean (hopefully).

**Comment by evaklopp** [comment]
What we found out about my point Nr. 2: the error depends on the ticker. There are 3 scenarios:
- disco with proper value
- disco with wrong value (or no connection to disco)
- not a disco

For some of them server responds with 404. @mkristian please define a story for solving that issue, if there is none yet.

**Comment by evaklopp** [comment]
@eharit could you please check and adjust the alignment of the column-items? they don´t seem to be consistent. 
Another thing: It is not very readable/usable that we don´t have more space for the PT-names. We should iterate the design here.

**Comment by evaklopp** [comment]
@scsirdx translation for Nr. 6: My Groups=Meine Gruppe, Powertaker=Stromnehmer. 
Do we need a whole story to translate all breadcrumb items at once? Would that make sense? Or is it simply the page title?

**Comment by evaklopp** [comment]
@scsirdx at the moment I don´t understand the sorting behaviour of the different columns. 
Clear to mee is 
-Name (A-Z)
-Begin and end date of the contract. 

the columns register name, contract number, status do not really sort. 
as a user I would expect the following: 

register name: sort A-Z and 1-n+1, 
contract number: raising contract number, even after the "/" 
status: by status. 

as this is not defined in the DoD, it would be fair enough if we define a new ticket for that. But if it is not a huge thing, also fine if you just implement it. Please tell me.

**Comment by phillipoertel** [comment]
Regarding the deduplication (#132), there's nothing left to be done in this ticket.
