### ISSUE TITLE
As Pho I want to login into the system with my own user credentials. 

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#3]
PR: 
- https://github.com/buzzn/buzzn/pull/1284
- https://github.com/buzzn/admin-app/pull/235
---
**Story:**
As PhO, I want to login into the system with my own user credentials. 

---
**Definition of done**
- [x] PHO gets the link to the logIn-site (https://staging-admin.buzzn.io)
- [x] PHO has a username and password (dev+ops@buzzn.net, password: Example123)
- [x] PHO can type his credentials into login fields
- [x] PHO gets linked to the "all my groups"-site after he puts in his credentials correctly
- [x] PHO is provided with an overall German errormessage when his username or pw is not valid

---
**Technical details**
- [x] restyle login screen according to design 
- [x] replace the hard-coded messages with ones loaded from language files
- [x] allow form submit on Enter
- [x] make cursor a pointer when hovering over the button
- [x] in case credentials are wrong, send the correct http status (401 Unauthorized) instead of 500
- [x] display error message on top of the form (for now; final notification system yet to be designed)
- [x] translate the login UI to German
- [x] (no password forgotten feature yet, hide it)

use the following PW to enter the screens: Wolfgang 

**LogIn Screen:** 
https://invis.io/8DDUMF34P#/256909740_Desktop_HD_-_Login

**Error messages:** 
https://invis.io/8DDUMF34P#/256909732_Controls

**Comment by evaklopp** [comment]
If I open the logIn - site with firefox 57.0 Quantum I see the fields not in default but the Username highlighted with a blue line and the PW-field with a red line like an error message. Like this: 
![bildschirmfoto 2017-11-15 um 16 24 54](https://user-images.githubusercontent.com/22292464/32844563-0a86fbce-ca23-11e7-8611-986092bd6654.png)

**Comment by eharit** [comment]
Yep, it's been already fixed in the current buzzn-style CSS.

**Comment by phillipoertel** [comment]
@eva we just fixed this on staging, please try again!

Looks like this for me now (Firefox Quantum / 57)
![bildschirmfoto 2017-11-15 um 17 23 26](https://user-images.githubusercontent.com/5188/32847425-3c01a8c8-ca2a-11e7-8e56-1c4855a9226d.png)

**Comment by dottorer** [comment]
@mkristian / @scsirdx : _NOTE: Chrome only issue_

I just tried the login and get the following sequence:
1. go to URL https://staging-admin.buzzn.io
2. enter 'dev+ops@buzzn.net' as username and password 'Ex....'
3. Hit Enter, and I get 'Password or Username are incorrect'
4. Without changes, I hit enter again, the app opens to the group list view.

Why is there are first refusal still happening for me in Chrome? Is there some weird password caching thing for Chrome? We don't need to trace it down if it is only me, but wanted to check.

**Comment by scsirdx** [comment]
@mkristian Same bug :(  /login req is in "pending" state.
Is your fix on staging already?

**Comment by evaklopp** [comment]
I don´t have this bug described by Ralf and Kristian with Chrome 61.0.3163.100 on my laptop.

**Comment by evaklopp** [comment]
Yay!
